export const modules = [
  { id: 'dashboard', label: 'Dashboard' },
  { id: 'licenses', label: 'Activar licencias' },
  {
    id: 'catalog',
    label: 'Catálogo',
    children: [
      { id: 'products', label: 'Productos' },
      { id: 'variants', label: 'Variantes' },
      { id: 'batches', label: 'Lotes' },
    ],
  },
  { id: 'customers', label: 'Clientes' },
  { id: 'providers', label: 'Proveedores' },
  { id: 'users', label: 'Usuarios' },
  { id: 'roles', label: 'Roles' },
  { id: 'activations', label: 'Ya activadas' },
  { id: 'audit', label: 'Auditoría' },
]

export const tableConfig = {
  licenses: {
    path: '/licenses',
    title: 'Licencias por activar',
    columns: [
      ['commercial_identifier', 'ID comercial público'],
      ['product_name', 'Producto'],
      ['variant_name', 'Variante'],
      ['masked_code', 'Clave única enmascarada'],
      ['status', 'Estado'],
      ['activation_priority_date', 'Atender antes de'],
      ['activation_priority_reason', 'Motivo'],
      ['responsible_user_name', 'Custodio'],
      ['created_by_name', 'Registrado por'],
    ],
  },
  batches: {
    path: '/batches',
    title: 'Lotes',
    columns: [
      ['batch_number', 'Lote'],
      ['product_name', 'Producto'],
      ['variant_name', 'Variante'],
      ['provider_name', 'Proveedor'],
      ['quantity', 'Cantidad comprada'],
      ['registered_licenses', 'Licencias registradas'],
      ['available_to_register', 'Disponibles por registrar'],
      ['activated_licenses', 'Activadas'],
      ['reserved_licenses', 'Reservadas'],
      ['expired_licenses', 'Vencidas'],
      ['status', 'Estado'],
    ],
  },
  products: {
    path: '/products',
    title: 'Productos',
    columns: [
      ['name', 'Nombre'],
      ['description', 'Descripción'],
      ['active', 'Activo'],
    ],
  },
  variants: {
    path: '/variants',
    title: 'Variantes',
    columns: [
      ['product_name', 'Producto'],
      ['name', 'Variante'],
      ['default_code', 'Código'],
      ['billing_cycle', 'Ciclo'],
      ['default_cost', 'Costo'],
    ],
  },
  customers: {
    path: '/customers',
    title: 'Clientes',
    columns: [
      ['name', 'Nombre'],
      ['tax_id', 'Documento'],
      ['email', 'Correo'],
      ['phone', 'Teléfono'],
      ['active', 'Activo'],
    ],
  },
  providers: {
    path: '/providers',
    title: 'Proveedores',
    columns: [
      ['name', 'Nombre'],
      ['contact_name', 'Contacto'],
      ['email', 'Correo'],
      ['phone', 'Teléfono'],
      ['active', 'Activo'],
    ],
  },
  users: {
    path: '/users',
    title: 'Usuarios',
    columns: [
      ['name', 'Nombre'],
      ['email', 'Correo'],
      ['role_name', 'Rol'],
      ['active', 'Activo'],
      ['last_login_at', 'Último ingreso'],
    ],
  },
  roles: {
    path: '/roles',
    title: 'Roles',
    columns: [
      ['name', 'Nombre'],
      ['description', 'Descripción'],
      ['active', 'Activo'],
    ],
  },
  activations: {
    path: '/activations',
    title: 'Ya activadas',
    columns: [
      ['commercial_identifier', 'ID comercial público'],
      ['product_name', 'Producto'],
      ['variant_name', 'Variante'],
      ['customer_name', 'Cliente'],
      ['device_reference', 'Dispositivo'],
      ['activated_by_name', 'Activó'],
      ['activation_date', 'Activación'],
      ['next_renewal_date', 'Vencimiento'],
      ['days_remaining', 'Días restantes'],
    ],
  },
  audit: {
    path: '/audit-logs',
    title: 'Auditoría',
    columns: [
      ['entity_name', 'Entidad'],
      ['entity_id', 'ID'],
      ['action', 'Acción'],
      ['user_name', 'Usuario'],
      ['ip_address', 'IP'],
      ['created_at', 'Fecha'],
    ],
  },
}

export const formConfig = {
  licenses: {
    guideText: 'Para crear una licencia necesitas un lote y un responsable. Si el lote no existe, créalo desde este mismo formulario.',
    options: [
      {
        name: 'batch_id',
        path: '/batches?limit=100',
        labelKey: 'batch_number',
        secondaryKey: 'variant_name',
        createModule: 'batches',
        createLabel: 'Crear lote',
      },
      {
        name: 'responsible_user_id',
        path: '/users?limit=100',
        labelKey: 'name',
        secondaryKey: 'email',
        createModule: 'users',
        createLabel: 'Crear usuario',
      },
    ],
    fields: [
      { name: 'batch_id', label: 'Lote', type: 'select', required: true, optionSource: 'batch_id' },
      { name: 'responsible_user_id', label: 'Custodio inicial', type: 'select', required: true, optionSource: 'responsible_user_id' },
      { name: 'name', label: 'Nombre', required: true, maxLength: 180 },
      {
        name: 'commercial_identifier',
        label: 'ID comercial público',
        required: true,
        maxLength: 180,
        pattern: '[A-Za-z0-9][A-Za-z0-9._/#: +()\\-]{1,179}',
        title: 'Puede ser un ID OEM, Retail/FPP, contrato, SKU o identificador público del proveedor.',
        help: 'Visible para soporte o distribuidores. Identifica producto, contrato o canal comercial; no activa el software.',
        transform: 'uppercase',
      },
      {
        name: 'license_code',
        label: 'Nueva clave única de activación',
        type: 'password',
        maxLength: 29,
        pattern: '([A-Za-z0-9]{4}-[A-Za-z0-9]{4}-[A-Za-z0-9]{4}-[A-Za-z0-9]{4}-[A-Za-z0-9]{4}|[A-Za-z0-9]{5}-[A-Za-z0-9]{5}-[A-Za-z0-9]{5}-[A-Za-z0-9]{5}-[A-Za-z0-9]{5}|[A-Za-z0-9]{20}|[0-9]{4}-[0-9]{4}-[0-9]{4}-[0-9]{4}-[0-9]{4}-[0-9]{4})',
        title: 'Formatos válidos: ESET 5 bloques de 4, Microsoft 5 bloques de 5, Kaspersky 20 caracteres corridos, Adobe 6 bloques numéricos de 4.',
        help: 'Confidencial. El formato depende del fabricante; se cifra al guardar y nunca se lista completa.',
        transform: 'uppercase',
      },
      {
        name: 'status',
        label: 'Estado',
        type: 'select',
        staticOptions: [
	          { value: 'available', label: 'Disponible para activar' },
	          { value: 'reserved', label: 'Reservada para cliente' },
	          { value: 'expired', label: 'Vencida' },
	          { value: 'cancelled', label: 'Cancelada' },
        ],
      },
      {
        name: 'validity_start_mode',
        label: 'Tipo de compra / inicio de vigencia',
        type: 'select',
        required: true,
        staticOptions: [
          { value: 'purchase_date', label: 'Compra online/oficial: vence desde la compra' },
          { value: 'first_activation', label: 'Física/distribuidor: vence desde la primera activación' },
        ],
      },
      { name: 'start_date', label: 'Fecha de compra/facturación', type: 'date' },
      { name: 'redeem_deadline_date', label: 'Fecha límite de canje', type: 'date' },
      { name: 'expiration_date', label: 'Fecha de vencimiento', type: 'date' },
      { name: 'cost', label: 'Costo', type: 'number', min: 0, step: '0.01', required: true },
      {
        name: 'billing_cycle',
        label: 'Ciclo',
        type: 'select',
        required: true,
        staticOptions: [
          { value: 'monthly', label: 'Mensual' },
          { value: 'annual', label: 'Anual' },
        ],
      },
      { name: 'currency_code', label: 'Moneda', maxLength: 3, defaultValue: 'PEN', transform: 'uppercase' },
      { name: 'notes', label: 'Notas', type: 'textarea', maxLength: 2000, full: true },
      { name: 'active', label: 'Activo', type: 'checkbox', defaultValue: true },
    ],
  },
  products: {
    guideText: 'Primero registra el producto base. Al guardar, el sistema continuará con la variante de ese producto.',
    fields: [
      { name: 'name', label: 'Nombre', required: true, maxLength: 180 },
      { name: 'description', label: 'Descripción', type: 'textarea', maxLength: 2000, full: true },
      { name: 'active', label: 'Activo', type: 'checkbox', defaultValue: true },
    ],
  },
  variants: {
    guideText: 'Una variante pertenece a un producto. Define su ciclo, costo y duración antes de crear lotes.',
    options: [
      {
        name: 'product_id',
        path: '/products?limit=100',
        labelKey: 'name',
        createModule: 'products',
        createLabel: 'Crear producto',
      },
    ],
    fields: [
      { name: 'product_id', label: 'Producto', type: 'select', required: true, optionSource: 'product_id' },
      { name: 'name', label: 'Variante', required: true, maxLength: 180 },
      { name: 'default_code', label: 'Código interno', maxLength: 100 },
      {
        name: 'billing_cycle',
        label: 'Ciclo',
        type: 'select',
        required: true,
        staticOptions: [
          { value: 'monthly', label: 'Mensual' },
          { value: 'annual', label: 'Anual' },
        ],
        defaultValue: 'annual',
      },
      { name: 'duration_days', label: 'Duración en días', type: 'number', min: 1 },
      { name: 'default_cost', label: 'Costo por defecto', type: 'number', min: 0, step: '0.01', defaultValue: 0 },
      { name: 'currency_code', label: 'Moneda', maxLength: 3, defaultValue: 'PEN', transform: 'uppercase' },
      { name: 'active', label: 'Activo', type: 'checkbox', defaultValue: true },
    ],
  },
  batches: {
    guideText: 'Un lote agrupa licencias de una variante. Aquí sí se selecciona proveedor porque el lote registra la compra.',
    options: [
      {
        name: 'variant_id',
        path: '/variants?limit=100',
        labelKey: 'name',
        secondaryKey: 'product_name',
        createModule: 'variants',
        createLabel: 'Crear variante',
      },
      {
        name: 'provider_id',
        path: '/providers?limit=100',
        labelKey: 'name',
        createModule: 'providers',
        createLabel: 'Crear proveedor',
      },
    ],
    fields: [
      { name: 'variant_id', label: 'Variante', type: 'select', required: true, optionSource: 'variant_id' },
      { name: 'provider_id', label: 'Proveedor', type: 'select', required: true, optionSource: 'provider_id' },
      {
        name: 'batch_number',
        label: 'Código de lote',
        maxLength: 100,
        placeholder: 'Automático: LOT-2026-0001',
        help: 'Déjalo vacío para que el sistema asigne el siguiente código disponible.',
      },
      { name: 'purchase_date', label: 'Fecha de compra', type: 'date', required: true },
      { name: 'quantity', label: 'Cantidad', type: 'number', min: 1, required: true },
      { name: 'unit_cost', label: 'Costo unitario', type: 'number', min: 0, step: '0.01', required: true },
      { name: 'currency_code', label: 'Moneda', maxLength: 3, defaultValue: 'PEN', transform: 'uppercase' },
      {
        name: 'status',
        label: 'Estado',
        type: 'select',
        defaultValue: 'draft',
        staticOptions: [
          { value: 'draft', label: 'Borrador' },
          { value: 'confirmed', label: 'Confirmado' },
          { value: 'cancelled', label: 'Cancelado' },
        ],
      },
      { name: 'notes', label: 'Notas', type: 'textarea', maxLength: 2000, full: true },
      { name: 'active', label: 'Activo', type: 'checkbox', defaultValue: true },
    ],
  },
  providers: {
    guideText: 'Registra solo datos del proveedor. No se crearán productos automáticamente desde aquí.',
    fields: [
      { name: 'name', label: 'Nombre', required: true, maxLength: 180 },
      { name: 'tax_id', label: 'Documento fiscal', maxLength: 30 },
      { name: 'contact_name', label: 'Contacto', maxLength: 150 },
      { name: 'email', label: 'Correo', type: 'email', maxLength: 255 },
      { name: 'phone', label: 'Teléfono', maxLength: 40 },
      { name: 'notes', label: 'Notas', type: 'textarea', maxLength: 2000, full: true },
      { name: 'active', label: 'Activo', type: 'checkbox', defaultValue: true },
    ],
  },
  customers: {
    guideText: 'Registra los datos del cliente para futuras activaciones o trazabilidad.',
    fields: [
      { name: 'name', label: 'Nombre', required: true, maxLength: 180 },
      { name: 'tax_id', label: 'Documento', maxLength: 30 },
      { name: 'email', label: 'Correo', type: 'email', maxLength: 255 },
      { name: 'phone', label: 'Teléfono', maxLength: 40 },
      { name: 'notes', label: 'Notas', type: 'textarea', maxLength: 2000, full: true },
      { name: 'active', label: 'Activo', type: 'checkbox', defaultValue: true },
    ],
  },
  users: {
    guideText: 'Crea el usuario y asigna su rol. Si el rol no existe, puedes crearlo aquí mismo.',
    options: [
      {
        name: 'role_id',
        path: '/roles?limit=100',
        labelKey: 'name',
        createModule: 'roles',
        createLabel: 'Crear rol',
      },
    ],
    fields: [
      { name: 'role_id', label: 'Rol', type: 'select', required: true, optionSource: 'role_id' },
      { name: 'name', label: 'Nombre', required: true, maxLength: 150 },
      { name: 'email', label: 'Correo', type: 'email', required: true, maxLength: 255 },
      { name: 'password', label: 'Contraseña', type: 'password', requiredOnCreate: true, minLength: 8, maxLength: 128 },
      { name: 'active', label: 'Activo', type: 'checkbox', defaultValue: true },
    ],
  },
  roles: {
    guideText: 'Define el rol administrativo. Los permisos reales se aplican según la configuración del sistema.',
    fields: [
      { name: 'name', label: 'Nombre', required: true, maxLength: 80 },
      { name: 'description', label: 'Descripción', type: 'textarea', maxLength: 1000, full: true },
      { name: 'active', label: 'Activo', type: 'checkbox', defaultValue: true },
    ],
  },
}

export const rolePermissions = {
  administrator: {
    products: ['create', 'update', 'delete'],
    variants: ['create', 'update', 'delete'],
    batches: ['create', 'update', 'delete'],
    providers: ['create', 'update', 'delete'],
    customers: ['create', 'update', 'delete'],
    users: ['create', 'update', 'delete'],
    roles: ['create', 'update', 'delete'],
    licenses: ['create', 'update', 'delete', 'activate', 'reserve'],
  },
  license_user: {
    batches: ['create', 'update'],
    customers: ['create', 'update'],
    licenses: ['create', 'update', 'activate', 'reserve'],
  },
  viewer: {},
}
